version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers-legacy
    steps:
      - checkout
      - run: mvn install -q
  test:
    docker:
      - image: circleci/openjdk:11-jdk-browsers-legacy
    steps:
      - checkout
      - run: mvn verify -q
      - store_test_results:
          path: target/surefire-reports
  coverage:
    docker:
      - image: circleci/openjdk:11-jdk-browsers-legacy
    steps:
      - checkout
      - run: mvn clean test jacoco:report coveralls:report -q
workflows:
  version: 2
  build_test_coverage:
    jobs:
      - build
      - test
      - coverage